{
 "title": "Mini Obs POC - App Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP request rate (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri, method, status) (rate(http_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "JVM Heap Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "heap used"
    }
   ]
  },
  {
   "title": "HikariCP Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "active" }
   ]
  }
 ]
}